### ISSUE TITLE
Running DSPatch script in SniperSimulator

### ISSUE THREAD

**Issue by eliodilar** [cross-platform/dspatch#15]
Hello,

Aftyer have succefully build and test script DSPatch, i try to use it in sniperSimulator ( hardware simulator. http://snipersim.org/w/The_Sniper_Multi-Core_Simulator
have you ever seen that kind of error?

i have put to dir the LD_LIBRARY_PATH=$(pwd) , libDSPatch.so

/home/chapoul/sniper/fff: symbol lookup error: /home/chapoul/sniper/fff: undefined symbol: _ZN7DSPatch9Component14SetInputCount_EiRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE

**Comment by MarcusTomlinson** [comment]
I suggest you install DSPatch like this on the machine or VM that requires it:

```
git clone https://github.com/cross-platform/dspatch.git
cd dspatch
mkdir build
cd build
cmake ..
sudo make install
```

**Comment by eliodilar** [comment]
ok i restart, your DSPatchTutorial file past him correctly in the simulator, i retry.

thanks

**Comment by eliodilar** [comment]
it's a problem with the simulator, he doesn't recognize LD_LIBRARY_PATH=$(pwd) during running

**Comment by MarcusTomlinson** [comment]
You don't need LD_LIBRARY_PATH=$(pwd) anymore if you install DSPatch as above.

I may be misunderstanding the situation but it sounds like /home/chapoul/sniper/fff may be a x86 process trying to link against an x64 build of DSPatch. If this is the case, you'll need to build DSPatch for x86.

**Comment by eliodilar** [comment]
AAHhhhh! i have never think to that effectively after have watch simulator, taget is intel64 but in make file i see: lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/li

Building for x86 (intel64)
... exactly...

**Comment by eliodilar** [comment]
Do you know what change to cmake an x86 DSPatch, i have run clang but errors occured.

Cordially

**Comment by eliodilar** [comment]
solve, i have define gcc compilation for nehalem architecture ( architecture simulated).
