### ISSUE TITLE
Scripting language interface for main block

### ISSUE THREAD

**Issue by smartmic** [cross-platform/dspatch#17]
Hi there,
I have a question. When looking at the tutorial, I was wondering if the construction and ticking of a circuit inside the main block can be made more accessible through a scripting language, eg. Ruby, Python or Scheme.
I have no experience with SWIG or embedded scripting languages yet. By chance, are there already thoughts or experiences in this direction?
−Martin

**Comment by MarcusTomlinson** [comment]
This is something I've thought about but no real plans have been made just yet. Python is the most likely route I'd take, using this: https://github.com/cross-platform/ecs-python. Perhaps you'd like to take a look at this library and see what you can do with it?

**Comment by smartmic** [comment]
Thank you, I will have a look into it and also check other alternatives. I will post an update when I have found a working solution.
