### ISSUE TITLE
Are the components random ticked? Is there a better way? 

### ISSUE THREAD

**Issue by vacing** [cross-platform/dspatch#22]
```cpp
        // tick all internal components
        for ( auto& component : p->components )
        {
            component->Tick( mode );
        }

        // reset all internal components
        for ( auto& component : p->components )
        {
            component->Reset();
        }
```
According to the code above and the fact that there is no order restriction when add components, can I assume the components are random ticked? 
Is it will be better if we know the end components( eg. audio writter) in a circuit and tick them directly?
Or like the FFmpeg filter graph, schedule them accroding to their priority?

**Comment by MarcusTomlinson** [comment]
A component's Tick() method begins by populating its input bus from its input wires. To insure that these inputs are up-to-date, that component calls all of its input components' Tick() methods first - hence recursively called in all components going backward through the circuit. This means that regardless of the order of the components in `p->components` the circuit will always process from left to right.

**Comment by vacing** [comment]
Sorry for the slow reply for the two issues, I was trying to understand you answers according the source code of this project and dspatchables. 
Now I think I have a deeper understanding about this project, thank you very much for your quick reply.

I have studied some other DP framework for media processing, such as FFmpeg, gstreamer, flexcore, and in my opinion gst maybe is the most powerful one. But gst has it's drawback, suck as the rarely used glib, so I think is it possible to rewrite a gst-like framework based on cpp? Or I want to know what's the goal or the role model of  dspatch?

**Comment by MarcusTomlinson** [comment]
DSPatch uses a pull system model. This has always been the goal of the project, and I don't have any plans to change it.

More generally though, the overarching reason behind why things are done the way they are done here, is simplicity - both in how it is used and how it is implemented. I'm rather proud of the balance this project strikes between being both efficient and maintainable.

**Comment by vacing** [comment]
> DSPatch at its core is just a simple pull system. This has always been the goal of the project, and I don't have any plans to change it.

got it, thank you again, learned a lot from your design principle
