### ISSUE TITLE
Nested/Sub Flow : Flow reuse/encapsulation

### ISSUE THREAD

**Issue by nyue** [cross-platform/dspatch#28]
Is there a concept/mechanism to support flow reuse through nested/sub flow whereby a flow definition can be wrap up in a way that e.g. exposes salient inputs/outputs, when view from the outside, user only see those salient inputs/outputs like a function.

**Comment by MarcusTomlinson** [comment]
Sure, what you're after is a component like this: https://github.com/cross-platform/dspatchables/tree/master/Components/InOut

For example, connect one of these (let's call it `inComp`) to the input of a complex circuit, and one (let's call it `outComp`) to the circuit's output. Inject input(s) via `inComp.PushOutput()`, `Tick()` the circuit, and retrieve output(s) via `outComp.PopInput()`
