### ISSUE TITLE
Circular circuits don't work

### ISSUE THREAD

**Issue by Jonyleo** [cross-platform/dspatch#35]
This might be my misunderstanding of the feature "Feedback loops".

Recreate Issue:

Start from the tutorial project
 - Change step 4 to
```
// 4. Wire up the components inside the circuit
// ============================================
circuit->ConnectOutToIn( randBoolGen1, 0, logicAnd, 0 );
circuit->ConnectOutToIn( logicAnd, 0, logicAnd, 1 );
circuit->ConnectOutToIn( logicAnd, 0, boolPrinter, 0 );
```
Basically wire the output of the And Component to one of it's inputs

Expected:
Some true or false value printed depending on the random gen

Result:
Nothing, GetValue on the And and PrintBool components seem to return null;

**Comment by Jonyleo** [comment]
Turns out it was indeed a miss understanding, just had to se a default value for the first tick.

For anyone interested, if you get invalid input on the Process_ method, just set a default output however you would like.

**Comment by MarcusTomlinson** [comment]
Indeed :) Sorry I didn't get to answering before you figured it out :)
