### ISSUE TITLE
need complex demo

### ISSUE THREAD

**Issue by myseemylife** [cross-platform/dspatch#37]
firstly,thx for you guys offering such good code! I test DSPatch last day. and now i want write a more bigger demo.but need some help!
A1-
       \
          C1 -->D1
      /
B1-

can i embeded circuit into a  circuit ? 
A1  is    task1-->task2--->task3 (serial pipeline)
B1  is    task3,task4,task5(parallel pipeline)

when and how  to use  ProcessOrder::NoOrder?

**Comment by MarcusTomlinson** [comment]
Hi @myseemylife, thank you for your kind words :)

`ProcessOrder::OutOfOrder` is useful in optimising components that don't require their Process_() callbacks to be performed in sequential order.

An example of this could be gain in an audio stream. When gain is constant, it can be applied to audio buffers regardless of their order in the stream.

E.g. https://github.com/cross-platform/dspatchables/blob/master/Components/Gain/Gain.cpp#L57

More info that may be useful: https://github.com/cross-platform/dspatch/issues/16 & https://github.com/cross-platform/dspatch/issues/21

**Comment by myseemylife** [comment]
> Hi @myseemylife, thank you for your kind words :)
> 
> `ProcessOrder::OutOfOrder` is useful in optimising components that don't require their Process_() callbacks to be performed in sequential order.
> 
> An example of this could be gain in an audio stream. When gain is constant, it can be applied to audio buffers regardless of their order in the stream.
> 
> E.g. https://github.com/cross-platform/dspatchables/blob/master/Components/Gain/Gain.cpp#L57
> 
> More info that may be useful: #16 & #21

Geat!! i have done my work!! thx for your informaton. issue Closed!
