### ISSUE TITLE
sort out git version tags

### ISSUE THREAD

**Issue by weatherhead99** [cross-platform/dspatch#39]
Hi,
thanks for your wonderful library. I am currently trying to put together some distro packages for it, and whilst the latest release is labelled in the CMake file (and description) as "8.0.0", the output of `git describe` is `4.00-76-g83e39ef` and the output of `git describe --tags` is `7.0.1-15-g83e39ef`. I know there is now a tag `latest-linux` but it would be nice to retain separate tags for large release versions.

Thanks

**Comment by MarcusTomlinson** [comment]
Ok `git describe --tags` should be good now
