### ISSUE TITLE
Can a component output be wired to multiple component inputs?

### ISSUE THREAD

**Issue by axjollivier** [cross-platform/dspatch#44]
Hi @MarcusTomlinson,

Just wondering if DSPatch supports wiring the output pin of a component to more than one input pin, or must the user instantiate a broadcast component explicitly? I couldn't find an explicit mention of this, if I'm correct I would suggest adding a note somewhere, perhaps to Circuit::ConnectOutToIn().

Best regards,
JO

**Comment by MarcusTomlinson** [comment]
Hey @axjollivier, yeah an output can be connected to multiple inputs :)

https://github.com/cross-platform/dspatch/blob/master/include/dspatch/Circuit.h#L47

**Comment by axjollivier** [comment]
Perfect, thanks so much!
