### ISSUE TITLE
Suggest renaming ReleaseThread() to ReleaseNextThread()

### ISSUE THREAD

**Issue by axjollivier** [cross-platform/dspatch#48]
Hi @MarcusTomlinson ,

Just a suggestion given on a somewhat subjective basis, but the following block of code, in Component.cpp, would be easier to understand if ReleaseThread was called ReleaseNextThread instead. In that method, I read too fast and missed the "threadNo + 1" when trying to understand if re-entry into a component's Process_() method was possible, seeing the word "Next" would have been a good supplemental cue. Again, this is somewhat subjective but hopefully helpful feedback.

```
  if ( p->processOrder == ProcessOrder::InOrder && p->bufferCount > 1 )
  {
      // 6. wait for our turn to process
      p->WaitForRelease( bufferNo );

      // 7. call Process_() with newly aquired inputs
      Process_( p->inputBuses[bufferNo], p->outputBuses[bufferNo] );

      // 8. signal that we're done processing
      p->ReleaseNextThread( bufferNo );    // <== RENAMED
  }
```

Best regards.

**Comment by MarcusTomlinson** [comment]
Hey @axjollivier good point, this is updated in main now.
