### ISSUE TITLE
Does the project's flow graph support subgraphs?

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#51]
Does the project's flow graph support subgraphs?
Subgraph - Also a node that contains a complete graph.
how to create a Subflow Graph?

**Comment by MarcusTomlinson** [comment]
There's no built-in support for this no. You could achieve this by creating a Component that has a Circuit inside of it.

**Comment by libaineu2004** [comment]
> There's no built-in support for this no. You could achieve this by creating a Component that has a Circuit inside of it.

Ok, I see is the project, https://github.com/taskflow/taskflow. And I thought it was very similar to yours.
