### ISSUE TITLE
Async data/event

### ISSUE THREAD

**Issue by mfkiwl** [cross-platform/dspatch#52]
Many thanks for sharing this data centric programing framework. Actually I love it very much and think it will simplifies a lot of programming effort when dealing with streaming data.

After reading the docs, I come across a question that if there are async event, such as user input, or history data based decision branch, that generating data not synced with the main data stream, what is the best way to do with the DSPatch framework?

Best regards,
Xing

**Comment by mfkiwl** [comment]
Nice! I got the point. Can I ask if you have similar examples just as you mentioned “SetGain”?

**Comment by mfkiwl** [comment]
Thanks I read the Gain.cpp. Could you please point out the example you are referring to ? I tried hard and didn't find it.

**Comment by MarcusTomlinson** [comment]
You can see the component has a public method "SetGain()" here: https://github.com/cross-platform/dspatchables/blob/master/Components/Gain/Gain.cpp#L64 (this is the answer to your original question)

You can also see here that input 2 of the component can accept a gain value from another component (if you want that): https://github.com/cross-platform/dspatchables/blob/master/Components/Gain/Gain.cpp#L92

**Comment by mfkiwl** [comment]
Many thanks
