### ISSUE TITLE
The Signal.h file is missing, resulting in an error in compiling the Inout project

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#54]
1.The earlier version had the Signal.h file, but now the new version does not have this header file. causing a compilation error:
\DSPatchables\Components\InOut\InOut.h(64,44): error C2065: 'Signal': undeclared identifier

https://github.com/cross-platform/dspatch/tree/master/include/dspatch/Signal.h

2.cmake+msvc2019, Compile Error
1>------ Build started: Project: InOut, Configuration: Debug x64 ------
1>Automatic MOC for target InOut
1>InOut.cpp
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\InOut\InOut.cpp(79,47): error C2664: “bool DSPatch::Signal::MoveSignal(DSPatch::Signal &)” : cannot convert argument 1 from 'fast_any::any' to 'DSPatch::Signal &'
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\DSPatch\include\dspatch/Signal.h(214,21): message : See the declaration of "DSPatch::Signal::MoveSignal"
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\InOut\InOut.cpp(89,62): error C2664: “void DSPatch::SignalBus::MoveSignal(int,fast_any::any & )": cannot convert argument 2 from "_Ty2" to "fast_any::any &"
1> with
1>[
1> _Ty2=DSPatch::Signal
1>]
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\DSPatch\include\dspatch/SignalBus.h(187,24): message : See the declaration of "DSPatch::SignalBus::MoveSignal"
1>Completed generating project "InOut.vcxproj" - Failed.
========== Generated: 0 succeeded, 1 failed, 2 latest, 0 skipped ==========

**Comment by MarcusTomlinson** [comment]
The InOut component was fixed yesterday :) Pull the latest commit to DSPatchables
