### ISSUE TITLE
SocketIn.cpp(26,1): error C2059: syntax error: "}"

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#55]
dspatch-9.7.1
MSVC 2019

1.compile error, 
\DSPatchables\Components\Sockets\SocketInSocketIn.cpp

![image](https://github.com/cross-platform/dspatch/assets/11898277/fea0c95c-ef12-404a-8e41-6d20303e0a25)

1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(26,1): error C2059: syntax error: "}"
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(26,1): error C2143: syntax error: missing ';' (before '}')
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(29,1): error C2143: syntax error: missing ";" (before "{")
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(29,1): error C2447: "{": missing function header (is it an old-style form? )
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(80,52): error C2065: "fn": undeclared identifier
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(115,79): error C2065: "fn": undeclared identifier
1>E:\temp\svntmp\dspatcher\dspatcher-master\DSPatchables\Components\Sockets\SocketIn\SocketIn.cpp(119,60): error C2065: "fn": undeclared identifier

2.compile error, 
\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc\modules\interface\module_common_types.h
![image](https://github.com/cross-platform/dspatch/assets/11898277/e7654b59-213a-4680-ba77-22dc2788aaf2)

4>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,5): warning C4003: Insufficient "max" arguments for function-like macro call
4>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,5): error C2589: illegal token to the right of "(":"::"
4>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ): error C2062: Unexpected type 'unknown-type'
4>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,1): error C2059: syntax error: ")"
5>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,5): warning C4003: Insufficient "max" arguments for function-like macro call
5>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,5): error C2589: illegal token to the right of "(":"::"
5>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ): error C2062: Unexpected type 'unknown-type'
5>E:\temp\svntmp\dspatcher\dspatcher-master\build\DSPatchables\Components\WebRtc\webrtc-audio-processing-prefix\src\webrtc-audio-processing\webrtc/modules/interface/module_common_types.h(343 ,1): error C2059: syntax error: ")"

**Comment by MarcusTomlinson** [comment]
Ok this should be fixed now
