### ISSUE TITLE
aec and agc, Compile Error

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#56]
MSVC 2019 x64

1.aec and agc, Compile Error

![image](https://github.com/cross-platform/dspatch/assets/11898277/b944b2b8-9e7b-4f11-b83d-aa6637e8708f)

1>------ Build started: Project: webrtc-audio-processing, Configuration: Debug x64 ------
2>------ Build started: Project: Aec, Configuration: Debug x64 ------
2>Automatic MOC for target Aec
2>libwebrtc_audio_processing.a(audio_processing_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_processing_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(checks.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(checks.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_converter.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_converter.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(agc_agc_manager_direct.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(agc_agc_manager_direct.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_buffer.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_buffer.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_ring_buffer.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(audio_ring_buffer.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(beamformer_nonlinear_beamformer.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(beamformer_nonlinear_beamformer.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(processing_component.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(processing_component.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(echo_cancellation_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(echo_cancellation_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(echo_control_mobile_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(echo_control_mobile_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(gain_control_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(gain_control_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(high_pass_filter_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(high_pass_filter_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(intelligibility_intelligibility_enhancer.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(intelligibility_intelligibility_enhancer.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(level_estimator_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(level_estimator_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(noise_suppression_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(noise_suppression_impl.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(transient_transient_suppressor.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(transient_transient_suppressor.cc.obj) : error LNK2038: Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MDd_DynamicDebug' (in Aec.obj)
2>libwebrtc_audio_processing.a(voice_detection_impl.cc.obj) : error LNK2038: Mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' (in Aec.obj)
2>libwebrtc_audio_processing.a(voice_detecti

2.Error copying file (if different) from "/bin/libEGLd.dll" to "E:/temp/svntmp/dspatcher/dspatcher-master/build/DSPatcher/Debug/libEGLd.dll".
![image](https://github.com/cross-platform/dspatch/assets/11898277/90691df6-11bf-4257-ab37-48502e9075b7)

>Error copying file (if different) from "/bin/libEGLd.dll" to "E:/temp/svntmp/dspatcher/dspatcher-master/build/DSPatcher/Debug/libEGLd.dll".
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: command "setlocal
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\ bin\cmake.exe" -E copy_if_different E:/temp/svntmp/dspatcher/dspatcher-master/build/DSPatcher/../DSPatchables/DSPatch/Debug/DSPatch.dll E:/temp/svntmp/dspatcher/dspatcher-master /build/DSPatcher/Debug
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto:cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: setlocal
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\ bin\cmake.exe" -E copy_if_different /bin/libEGLd.dll E:/temp/svntmp/dspatcher/dspatcher-master/build/DSPatcher/Debug/libEGLd.dll
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto:cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: setlocal
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\ bin\cmake.exe" -E copy_if_different /bin/libGLESv2d.dll E:/temp/svntmp/dspatcher/dspatcher-master/build/DSPatcher/Debug/libGLESv2d.dll
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto:cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3

**Comment by MarcusTomlinson** [comment]
In order to use the WebRTC components, you need to set the CMAKE_BUILD_TYPE in your cmake call (See the “Build:” section in the README)

**Comment by libaineu2004** [comment]
> In order to use the WebRTC components, you need to set CMAKE_BUILD_TYPE in your cmake call (See the “Build” section in the README)

ok
