### ISSUE TITLE
Is there any way to get whether the operation of circuit->Tick() is completed?

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#57]
I tested the tutorial of the project
https://github.com/cross-platform/dspatch/tree/master/tutorial

If we set
circuit->SetBufferCount(0);
Then circuit->Tick(); is executed on the main thread;
If we set
circuit->SetBufferCount(4);
Then circuit->Tick(); is executed in the sub-thread;
my question is:
When the sub-thread is running, do we have a way to get whether circuit->Tick(); has finished running?
Is it possible to add a new function to obtain the end flag of this Tick operation?

**Comment by MarcusTomlinson** [comment]
Hey, I've just added a `circuit->Sync()` method for you.

**Comment by libaineu2004** [comment]
> Hey, I've just added a `circuit->Sync()` method for you.

thank you
