### ISSUE TITLE
Is the data structure used in this project DAG?

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatch#58]
DAG:Directed Acyclic Graph

1.Is the data structure of "circuit" a graph or a tree?
2.Is the data structure of adding "components" to "circuit" a graph or a tree? If it is a graph, is it acyclic or cyclic?
3.Is there any documentation that explains the principles of each component traversal? Is it depth-first or breadth-first?

**Comment by MarcusTomlinson** [comment]
Graph.

You can loopback if you want. Graphs can be cyclic or acyclic.

Pull-system. Each component pulls from its input components, and so on backward through the graph.

**Comment by libaineu2004** [comment]
> Graph.
> 
> You can loopback if you want. Graphs can be cyclic or acyclic.
> 
> Pull-system. Each component pulls from its input components, and so on backward through the graph.

oh oh. That is to say, the DSPatch::Circuit in our project supports cyclic. 

Thanks
